config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login , sign_out: :logout }

  resources :badges, only: :index
  get 'badges/collected', to: "badges#collected", as: "collected_badges"

  resources :contacts, only: :create
  get 'contact-us', to: "contacts#new", as: "new_contact"

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  # GET /test_passages/101/result
  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :badges
    resources :gists, only: :index
  end

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers
  has_many :gists

  validates :body, presence: true
end

app/models/test_passage.rb
class TestPassage < ApplicationRecord
  belongs_to :test
  belongs_to :user
  belongs_to :current_question, class_name: 'Question', optional: true

  before_validation :before_validation_set_question, on: %i[create update]

  scope :passed, -> { where(success: true) }

  SUCCESS_SCORE = 85

  def test_passed?
    success_percentage >= SUCCESS_SCORE && !time_is_up?
  end

  def completed?
    current_question.nil?
  end

  def accept!(answer_ids)
    if correct_answer?(answer_ids) && !time_is_up?
      self.correct_questions += 1
    end
    self.success = test_passed?

    save!
  end

  def timer_finish_time
    created_at + test.timer.minutes
  end

  def time_is_up?
    test.timer? && timer_finish_time.past?
  end

  def success_percentage
    (correct_questions / total_questions.to_f) * 100
  end

  def total_questions
    test.questions.count
  end

  def current_question_number
    current_question_index + 1
  end

  def current_question_index
    test.questions.index(current_question)
  end

  private

  def before_validation_set_question
    if current_question.nil? && test.present?
      set_first_question
    else
      set_next_question
    end
  end

  def set_first_question
    self.current_question = test.questions.first
  end

  def set_next_question
    self.current_question = next_question
  end

  def correct_answer?(answer_ids)
    correct_answers.ids.sort == Array(answer_ids).map(&:to_i).sort
  end

  def correct_answers
    current_question.answers.correct
  end

  def next_question
    remaining_questions.first
  end

  def remaining_questions
    test.questions.order(:id).where('id > ?', current_question.id)
  end

end

app/controllers/test_passages_controller.rb
class TestPassagesController < ApplicationController

  before_action :set_test_passage, only: %i[show update result gist]

  def show
  end

  def result
    if @test_passage.test_passed?
      @badges = BadgeGranterService.new(@test_passage).achievements
    end
  end

  def gist
    gist_service = GistQuestionService.new(@test_passage.current_question)
    result = gist_service.call
    gist_url = result.html_url

    flash_options = if gist_service.success?
                      gist_url_tag = %(<a href="#{gist_url}" target="_blank">gist.github.com</a>)
                      current_user.gists.create(question: @test_passage.current_question,
                                                url: gist_url)
                      { notice: t('.success', url: gist_url_tag) }
                    else
                      { alert: t('.failure') }
                    end

    redirect_to @test_passage, flash_options
  end

  def update
    @test_passage.accept!(params[:answer_ids])

    if @test_passage.completed?
      if @test_passage.test_passed?
        BadgeGranterService.new(@test_passage).call
      end

      TestsMailer.completed_test(@test_passage).deliver_now
      redirect_to result_test_passage_path(@test_passage)
    else
      render :show
    end
  end

  private

  def set_test_passage
    @test_passage = TestPassage.find(params[:id])
  end
end

app/helpers/test_passages_helper.rb
module TestPassagesHelper

  def success_percentage_result_message(test_passage)
    if test_passage.test_passed?
      result_status = 'success'
      message = t('test_passages_helper.result.success')
    else
      result_status = 'fail'
      message = t('test_passages_helper.result.fail')
    end

    result_body = [div_percentage_helper(test_passage.success_percentage, result_status),
                   content_tag(:p, message)]

    result_body.join.html_safe
  end

  # result_status == ['success', 'fail']
  def div_percentage_helper(number, result_status)
    content_tag(:div, class: "percentage #{result_status}") do
      number_to_percentage(number, precision: 0)
    end
  end

  def header_current_question(test_passage)
    content_tag(:p) do
      "#{t('test_passages_helper.current_question')}: #{test_passage.current_question_number} /
        #{test_passage.total_questions}"
    end
  end

  def header_current_progress(test_passage)
    test_passage.current_question_index / test_passage.total_questions.to_f * 100
  end

end

app/views/test_passages/_form.html.erb
<%= form_with url: test_passage_path(@test_passage), local: true, method: :put,
              class: 'testpassage-form', data: { testpassage_id: @test_passage.id } do |form| %>

  <%= form.collection_check_boxes :answer_ids,
                                  @test_passage.current_question.answers,
                                  :id, :body, include_hidden: false do |b| %>
    <div class="form-check">
      <p>
        <%= b.check_box id: "answer_ids_#{b.object.id}", class: 'form-check-input' %>
        <%= b.label class: 'form-check-label'%>
      </p>
    </div>
  <% end %>

  <p><%= link_to t('test_passages_helper.gist_question'), gist_test_passage_path(@test_passage),
                 method: :post %></p>
  <%= form.submit t('test_passages_helper.next_button'), class: "btn btn-primary" %>

<% end %>

app/views/test_passages/_header_and_question.html.erb
<%= header_current_question(@test_passage) %>

<% percent = header_current_progress(@test_passage) %>

<%= content_tag :div, class: "progress", data: { percent: percent } do %>
  <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar"
       aria-valuemin="0" aria-valuemax="100"></div>
<% end %>

<div class="card-header">
  <h5 class="card-title">
    <%= @test_passage.current_question.body %>
  </h5>
</div>

app/views/test_passages/result.html.erb
<div class="row justify-content-md-center mt-3 ">
  <div class="col-md-auto mb-3">
    <h1><%= t('.header', title: @test_passage.test.title) %></h1>

    <p>
      <%= t('.all_quesions_number', total_questions: @test_passage.total_questions) %> <br>
      <%= t('.questions_with_correct_answers', correct_questions: @test_passage.correct_questions) %>
    </p>

    <%= render 'badges/badge_table' %>

    <div class="card text-center mb-3">
      <div class="card-body">
        <%= success_percentage_result_message(@test_passage) %> <br>
        <%= link_to t('.all_tests'), tests_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/test_passages/show.html.erb
<h1><%= t('.header', test_passage_test_title: @test_passage.test.title) %></h1>

<% if @test_passage.current_question.nil? %>

  <p>
    <%= t('.no_available_questions') %><br>
  </p>

  <%= link_to t('navigation.back'), tests_path, class: "btn btn-primary" %>

<% elsif @test_passage.current_question.answers.count.zero? %>

  <%= render 'header_and_question' %>

  <div class="card card-body">
    <%= t('.no_available_answers') %>
  </div>

  <p>
    <%= link_to t('navigation.back'), tests_path, class: "btn btn-primary mt-3" %>
  </p>

<% else %>

  <%= render 'header_and_question' %>

  <div class="card card-body mb-3">
    <%= render 'form' %>
  </div>

  <% if @test_passage.test.timer %>
    <b><%= t('.remaining_time') %>:</b>
    <%= content_tag :span, '', id: :timer,
                    data: { timer: @test_passage.timer_finish_time.to_s } %>
    <%= t('.minutes') %>.
  <% end %>

<% end %>