config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login , sign_out: :logout }

  resources :badges, only: :index
  get 'badges/collected', to: "badges#collected", as: "collected_badges"

  resources :contacts, only: :create
  get 'contact-us', to: "contacts#new", as: "new_contact"

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  # GET /test_passages/101/result
  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :badges
    resources :gists, only: :index
  end

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :body, presence: true

  validate :validate_max_answers_count, on: :create

  scope :correct, -> { where(correct: true) }

  private

  def validate_max_answers_count
    message = 'can only have maximum 4 answers!'
    errors.add(:question, message) if question.answers.count >= 4
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController

  before_action :set_question, only: %i[new create]
  before_action :set_answer, only: %i[show edit update destroy]

  def show
  end

  def new
    @answer = @question.answers.new
  end

  def edit
  end

  def create
    @answer = @question.answers.new(answer_params)

    if @answer.save
      redirect_to [:admin, @answer], notice: t('.success')
    else
      render :new
    end
  end

  def update
    if @answer.update(answer_params)
      redirect_to [:admin, @answer], notice: t('.success')
    else
      render :edit
    end
  end

  def destroy
    @answer.destroy
    redirect_to [:admin, @answer.question], notice: t('.success')
  end

  private

  def set_question
    @question = Question.find(params[:question_id])
  end

  def set_answer
    @answer = Answer.find(params[:id])
  end

  def answer_params
    params.require(:answer).permit(:body, :correct)
  end
end

app/views/admin/answers/_answer.html.erb
<li class="list-group-item <%= "list-group-item-success" if answer.correct %>">
  <%= answer.body %>  <br>
  <%= link_to t('actions.show'), admin_answer_path(answer) %> |
  <%= link_to t('actions.edit'), edit_admin_answer_path(answer) %> |
  <%= link_to t('actions.delete'),
              admin_answer_path(answer),
              method: :delete,
              data: { confirm: t('actions.delete_confirmation') } %>
</li>

app/views/admin/answers/_form.html.erb
<div class="card border-primary">
  <div class="card-body">
    <%= form_with(model: [:admin, @question, @answer], local: true) do |form| %>

      <%= render 'shared/errors', resource: @answer %>

      <div class="form-group">
        <p>
          <%= form.label :body %> <br>
          <%= form.text_area :body, id: :answer_body, rows: 7, cols: 60, class: 'form-control' %>
        </p>

        <div class="form-check">
          <%= form.label :correct, class: 'form-check-label' do %>
            <%= form.check_box :correct, class: 'form-check-input' %>
            <%= t('admin.answers.correct_answer_question')  %>
          <% end %>
        </div>

        <p><%= form.submit class: "btn btn-outline-primary mt-3" %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/answers/edit.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-6">
    <h1><%= t('.header') %></h1>

    <p>
      <%= @answer.question.body %>
    </p>

    <%= render 'form' %>
    <%= link_to t('navigation.back'), admin_question_path(@answer.question), class: "btn btn-primary mt-3" %>
  </div>
</div>

app/views/admin/answers/new.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-6">
    <h1><%= t('.header') %></h1>

    <p>
      <%= @question.body %>
    </p>

    <%= render 'form' %>
    <%= link_to t('navigation.back'), admin_question_path(@question), class: "btn btn-primary mt-3" %>
  </div>
</div>

app/views/admin/answers/show.html.erb
<div class="row justify-content-md-center">
  <div class="col-md-5 mb-3">
    <div class="card mt-3 mb-3">
      <div class="card-header">
        <h1 class="card-title">
          <%= t('.header') %>
        </h1>
      </div>

      <div class="card-body">
        <p class="card-text mt-2">
          <%= @answer.question.body %>
        </p>
      </div>
    </div>
  </div>

  <div class="col-md-7 mt-3 mb-3">
    <p>
      <b><%= t('.answer') %>:</b>
      <%= @answer.body %>
    </p>

    <p>
      <b><%= t('.correct') %>:</b>
      <%= @answer.correct %>
    </p>

    <%= link_to t('navigation.back'), admin_question_path(@answer.question), class: "btn btn-primary" %>
  </div>
</div>