config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login , sign_out: :logout }

  resources :badges, only: :index
  get 'badges/collected', to: "badges#collected", as: "collected_badges"

  resources :contacts, only: :create
  get 'contact-us', to: "contacts#new", as: "new_contact"

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  # GET /test_passages/101/result
  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :badges
    resources :gists, only: :index
  end

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers
  has_many :gists

  validates :body, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController

  before_action :set_test, only: [:new, :create]
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def show
  end

  def new
    @question = @test.questions.new
  end

  def create
    @question = @test.questions.new(question_params)

    if @question.save
      redirect_to admin_test_path(@test), notice: t('.success')
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @question.update(question_params)
      redirect_to admin_test_path(@question.test), notice: t('.success')
    else
      render :edit
    end
  end

  def destroy
    @question.destroy
    redirect_to admin_test_path(@question.test), notice: t('.success')
  end

  private

  def set_test
    @test = Test.find(params[:test_id])
  end

  def set_question
    @question = Question.find(params[:id])
  end

  def question_params
    params.require(:question).permit(:body, :test_id)
  end

  def rescue_with_question_not_found
    render plain: t('shared.errors.rescue_with_question_not_found')
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
  def question_header(question)
    test_title = question.test.title

    name = if question.new_record?
             t('questions_helper.create.header', test_title: test_title)
           else
             t('questions_helper.edit.header', test_title: test_title)
           end

    content_tag('h1', name)
  end
end

app/views/admin/questions/_form.html.erb
<div class="card border-primary">
  <div class="card-body">
    <%= form_with model: [:admin, @test, @question], local: true do |form| %>

      <%= render 'shared/errors', resource: @question %>

      <div class="form-group">
        <p>
          <%= form.label :body %>
          <%= form.text_area :body, cols: 60, rows: 10, id: :question_body, class: 'form-control' %>
        </p>

        <p><%= form.submit class: "btn btn-outline-primary" %></p>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/questions/_list.html.erb
<p>
  <%= link_to t('.new_question'), new_admin_test_question_path(@test),
              class: "btn btn-outline-primary btn-lg" %>
</p>

<% if @test.questions.present? %>
  <table class="table table-striped table-hover">
    <thead class="thead-dark">
    <tr>
      <th><%= t('.table.body') %></th>
      <th class="text-center"><%= t('.table.actions') %></th>
    </tr>
    </thead>

    <%= render partial: 'admin/questions/question', collection: @test.questions %>

  </table>
<% else %>
  <p><%= t('.no_questions_available') %></p>
<% end %>

app/views/admin/questions/_question.html.erb
<tr>
  <td><%= question.body %></td>
  <td><%= link_to t('actions.show'), admin_question_path(question),
                  class: "btn btn-outline-primary btn-block" %>
    <%= link_to t('actions.edit'), edit_admin_question_path(question),
                class: "btn btn-outline-success btn-block" %>
    <%= link_to t('actions.delete'), admin_question_path(question),
                class: "btn btn-outline-danger btn-block btn-sm",
                method: :delete,
                data: { confirm: t('actions.delete_confirmation') } %>
  </td>
</tr>

app/views/admin/questions/edit.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-6">
    <%= question_header(@question) %>

    <%= render 'form' %>
    <%= link_to t('navigation.back'), admin_test_path(@question.test), class: "btn btn-primary mt-3" %>
  </div>
</div>

app/views/admin/questions/new.html.erb
<div class="row justify-content-center mt-3">
  <div class="col col-md-6">
    <%= question_header(@question) %>

    <%= render 'form' %>

    <%= link_to t('navigation.back'), admin_test_path(@question.test), class: "btn btn-primary mt-3" %>
  </div>
</div>

app/views/admin/questions/show.html.erb
<div class="row justify-content-md-center mt-3">
  <div class="col-md-5 mb-3">
    <div class="card">
      <div class="card-header">
        <h1 class="card-title">
          <%= t('.header', question_test_title: @question.test.title) %>
        </h1>
      </div>
      <div class="card-body">
        <p class="card-text mt-2">
          <%= @question.body %>
        </p>

        <%= link_to t('navigation.edit'), edit_admin_question_path(@question), class: "card-link" %> |
        <%= link_to t('navigation.back'), admin_test_path(@question.test), class: "btn btn-primary" %>
      </div>
    </div>
  </div>

  <div class="col-md-7 mb-3">
    <h2><%= t('.answers') %></h2>

    <%= link_to t('.new_answer'), new_admin_question_answer_path(@question),
                class: "btn btn-outline-primary mb-3" %>

    <ol class="list-group">
      <%= render @question.answers %>
    </ol>

  </div>
</div>