config/routes.rb
Rails.application.routes.draw do

  root 'tests#index'

  devise_for :users, path: :gurus, path_names: { sign_in: :login , sign_out: :logout }

  resources :badges, only: :index
  get 'badges/collected', to: "badges#collected", as: "collected_badges"

  resources :contacts, only: :create
  get 'contact-us', to: "contacts#new", as: "new_contact"

  resources :tests, only: :index do
    member do
      post :start
    end
  end

  # GET /test_passages/101/result
  resources :test_passages, only: %i[show update] do
    member do
      get :result
      post :gist
    end
  end

  namespace :admin do
    resources :tests do
      patch :update_inline, on: :member

      resources :questions, shallow: true, except: :index do
        resources :answers, shallow: true, except: :index
      end
    end

    resources :badges
    resources :gists, only: :index
  end

end

app/views/layouts/_footer.html.erb
<footer class="bg-dark mt-4">
  <div class="container-fluid py-3">
    <div class="row">
      <div class="col-md-6">
        <%= t('footer.app_description') %>
      </div>
      <div class="col-md-6 text-right small align-self-end">
        © 2018-<%= current_year %>,
        project: <%= github_url(user: 'aritode', repo: 'test-guru') %>
        by: <%= github_url(user: 'aritode') %>
        <br><%= link_to t('footer.app_description_with_url'),
                        "https://thinknetica.com/", target: '_blank' %>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-light bg-light">
    <%= link_to 'TestGuru', root_path, class: 'navbar-brand' %>

    <span class="navbar-text">
      <%= render 'layouts/navigation' %>
    </span>
  </nav>
</header>

app/views/layouts/_navigation.html.erb
<% if user_signed_in? %>
    <%= t('site_navigation.welcome') %>,
    <b><%= current_user.full_name.html_safe %></b> <%= t('site_navigation.guru') %> |
    <%= t('site_navigation.badges') %>:
    <%= link_to t('site_navigation.guru'), collected_badges_path %> /
    <%= link_to t('site_navigation.all'), badges_path %> |
    <% if current_user.admin? %>
      <%= link_to t('site_navigation.admin_panel'), admin_tests_path %> |
    <% end %>
    <%= link_to t('site_navigation.contact_us'), new_contact_path %> |
    <%= link_to t('site_navigation.log_out'), destroy_user_session_path, method: :delete %>
<% else %>
    <%= link_to t('site_navigation.log_in'), new_user_session_path %> <%= t('site_navigation.or') %>
    <%= link_to t('site_navigation.sign_up'), new_user_registration_path %>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Admin Panel | TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= javascript_tag do %>
      window.I18n = <%= common_translations.to_json.html_safe %>
    <% end %>
  </head>

  <body>
    <%= render 'admin/header' %>

    <div class="container">
      <%= render 'shared/flash_messages' %>
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>TestGuru</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <%= render 'shared/flash_messages' %>
      <%= yield %>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>